### ISSUE TITLE
CSVファイルをBOM付きにする

### ISSUE THREAD

**Issue by halsk** [codeforjapan/mynumbercard_statistics#114]
EXCELでそのまま開ける

**Comment by taisukef** [comment]
参考コード
https://github.com/code4sabae/covid19/blob/master/util.mjs

exports.addBOM = function (s) {
  return '\ufeff' + s
}
exports.removeBOM = function (s) {
  if (s.charAt(0) === '\ufeff') {
    return s.substring(1)
  }
  return s
}
