### ISSUE TITLE
8月分データが公開されました

### ISSUE THREAD

**Issue by taisukef** [codeforjapan/mynumbercard_statistics#147]
https://www.soumu.go.jp/kojinbango_card/
PDFとExcelでの公開となったようです

**Comment by halsk** [comment]
CSVやSpreadsheetの方はちゃんとアップデートされていますが、Tableau が更新されていない？

**Comment by taisukef** [comment]
ありがとうございます！
更新されてました
https://fukuno.jig.jp/app/opendatacity/mynumber7x7.html
