### ISSUE TITLE
demographics.csvの「全体」の「人口(女)」「人口(計)」の値が不正

### ISSUE THREAD

**Issue by ocean3fish** [codeforjapan/mynumbercard_statistics#148]
「全体」の「人口(女)」の値がnullで、「人口(計)」に2つの数値が入ってしまっている様子。
<img width="656" alt="スクリーンショット 2020-09-14 23 10 39" src="https://user-images.githubusercontent.com/4206675/93096789-c4e98680-f6df-11ea-95e5-3ee01672521b.png">

**Comment by halsk** [comment]
ありがとうございます。確認します
