### ISSUE TITLE
スマホ対応

### ISSUE THREAD

**Issue by halsk** [codeforjapan/mynumbercard_statistics#32]
Tableau の凡例を調整したい

**Comment by kaizumaki** [comment]
すごいおもしろそうなプロジェクトですね！こちらのissueやってみます（時間かかるようだったらDPRを出しておきます）。

**Comment by halsk** [comment]
おー、心強い。ありがとうございます！

**Comment by halsk** [comment]
@kaizumaki よくわかんないですけど、Tableau 側で設定しなくてはいけないかもしれません。

**Comment by kaizumaki** [comment]
@halsk そうなんですね。実はまだ環境設定で苦戦してます。 `make download` がすごい時間がかかっていて...

**Comment by kaizumaki** [comment]
手元環境で立ち上がりました。tableau部分は `tableau-react` が `tableau-2.3.0.js` をラップしてるんですね。TableauのJS APIでlegendを操作できるオプションがあればいいのですが。ちょっと探ってみます。

**Comment by halsk** [comment]
はい。make download, 一旦全てのデータをローカルに持ってくるので時間かかります。次回以降は早いはずです。
Tableau よくわかってませんが、Dashboard というのを作るとスマホ用のビューも作れるのか？
https://help.tableau.com/current/pro/desktop/ja-jp/dashboards.htm

**Comment by kaizumaki** [comment]
なるほど、ダッシュボードよさそうですね。異なるデバイスのレイアウト自動作成っていうのがありますね。
https://help.tableau.com/current/pro/desktop/ja-jp/dashboards_dsd_create.htm

**Comment by halsk** [comment]
下山さん作成バージョンの Tableau に切り替えたら、スマホ対応もできていました！
