### ISSUE TITLE
フィールド名を出典元に基づいた正確な表現に変更

### ISSUE THREAD

**Issue by ocean3fish** [codeforjapan/mynumbercard_statistics#76]
各csvのフィールド名について、
出典元に基づく&フィールド名を見ただけでできるだけ正確に解釈できるようにという方針を取る場合、
以下の通り変更すると良さそうです。

- demographics.csv
公開日 -> 算出基準日
交付件数基準日 -> 交付枚数算出基準日

- all_prefectures.csv
公開日 -> 算出基準日
交付率 -> 人口に対する交付枚数率
交付件数基準日 -> 交付枚数算出基準日

- summary_by_types.csv
公開日 -> 算出基準日
交付件数基準日 -> 交付枚数算出基準日

- all_localgovs.csv
公開日 -> 算出基準日
交付率 -> 人口に対する交付枚数率
交付件数基準日 -> 交付枚数算出基準日

あるいは、issue #71 （各CSVの解説を入れる）で対応でも良いかもしれません。

**Comment by ocean3fish** [comment]
@halsk こちらご対応頂きありがとうございました！
念のためTableau側を確認して、データの参照で不具合が出ていたら修正アップデートしておきますー。

**Comment by ocean3fish** [comment]
今回の変更現状のデータには反映されていなかったので、次回更新分から反映される予定でしょうか？
もし可能であれば全データ一気に変更できた方がヘッダ名の表記揺れが発生せずデータの使い勝手としては良さそうです。
ご検討ください。

**Comment by halsk** [comment]
@ocean3fish 本日Spreadsheet側にも取り込まれたと思います。ご確認いただけますか？

**Comment by ocean3fish** [comment]
こちら確認しました！ご対応ありがとうございます。
Tableau側もフィールド名の変更に対応させてアップデートしました。
