### ISSUE TITLE
Tableauをスマホで見たときに文字が出ない

### ISSUE THREAD

**Issue by halsk** [codeforjapan/mynumbercard_statistics#97]
![image](https://user-images.githubusercontent.com/16509/88364023-b86e3f00-cdbc-11ea-996b-71adbf39eab4.png)

#### と表記されてしまっている

**Comment by halsk** [comment]
@ocean3fish さん、ご確認いただけると幸いです

**Comment by ocean3fish** [comment]
@halsk 不具合修正してアップデートしました。
私の環境（iPhoneX）では問題なく表示されています。

あとはダッシュボードサイズに合わせて、スマホの時の埋め込み領域の縦サイズを2,000pxに伸ばして頂くことは可能でしょうか？

![IMG_0532](https://user-images.githubusercontent.com/4206675/88386133-be7b1480-cdea-11ea-8589-559cae3eda5c.PNG)

**Comment by halsk** [comment]
ありがとうございます。了解です！

**Comment by halsk** [comment]
スマホの場合はiframeの枠を高く取るよう変更しました。
